### ISSUE TITLE
对象排序并去重——一道笔试题 | iced-cola

### ISSUE THREAD

**Issue by chenxii81** [chenxii81/chenxii81.github.io#12]
https://iced-cola.com/2020/10/27/%E5%AF%B9%E8%B1%A1%E6%8E%92%E5%BA%8F%E5%B9%B6%E5%8E%BB%E9%87%8D%E2%80%94%E2%80%94%E4%B8%80%E9%81%93%E7%AC%94%E8%AF%95%E9%A2%98/ 

 对象排序并去重——一道笔试题

**Comment by iced-cola** [comment]
今天上午收到通知，上面的答案通过了笔试，7.5分。
