### ISSUE TITLE
Ubuntu 18.04安装Mariadb修改初始密码 | iced-cola

### ISSUE THREAD

**Issue by chenxii81** [chenxii81/chenxii81.github.io#2]
https://iced-cola.com/2020/10/22/Ubuntu-18-04%E5%AE%89%E8%A3%85Mariadb%E4%BF%AE%E6%94%B9%E5%88%9D%E5%A7%8B%E5%AF%86%E7%A0%81/ 

 Ubuntu 18.04安装Mariadb修改初始密码

**Comment by iced-cola** [comment]
我之所以想变强，是为了活得轻松写意。
